<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Hashim Group CRM | {{ __('RESERVATION REPORT') }}: {{ $val }}</title>

    <style>

        body {
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            text-align: center;
            color: #777;
        }

        body h1 {
            font-weight: 300;
            margin-bottom: 0px;
            padding-bottom: 0px;
            color: #000;
        }

        .invoice-box {
            max-width: 100%;
            margin: 10px;
            padding: 10px;
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        .invoice-box table {
            width: 100%;
            line-height: inherit;
            text-align: left;
        }

        .invoice-box table td {
            padding: 5px;
            vertical-align: top;
        }

        .invoice-box table tr td:nth-child(2) {
            text-align: left;
        }

        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.top table td.title {
            font-size: 45px;
            line-height: 45px;
            color: #333;
        }

        .invoice-box table tr.information table td {
            padding-bottom: 40px;
        }

        .invoice-box table tr.heading td {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }

        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.item td {
            border-bottom: 1px solid #eee;
        }

        .invoice-box table tr.item.last td {
            border-bottom: none;
        }

        .invoice-box table tr.total td:nth-child(2) {
            border-top: 2px solid #eee;
            font-weight: bold;
        }

        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }

            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }
    </style>
</head>

<body>
<h1>
    {{ __('RESERVATION REPORT') }}{{ $val }}
</h1>
<div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
        <tr class="heading">
            <th>{{ __('Owner name') }}</th>
            <th>{{ __('CUSTOMER NAME') }}</th>
            <th>{{ __('Date') }}</th>
            <th>{{ __('Project name') }}</th>
            <th>{{ __('Province/Country') }}</th>
            <th>{{ __('Section/Plot') }}</th>
            <th>{{ __('Block No') }}</th>
            <th>{{ __('Floor No:') }}</th>
            <th>{{ __('No of Rooms') }}</th>
            <th>{{ __('Gross M²') }}</th>
            <th>{{ __('Flat No') }}</th>
            <th>{{ __('Reservation Amount') }}</th>
            <th>{{ __('Sale price') }}</th>
            <th>{{ __('Note') }}</th>
            <th>{{ __('Down payment') }}</th>
            <th>{{ __('Payment type') }}</th>
            <th>{{ __('Discount') }}</th>
        </tr>
        @foreach($deals as $key => $deal)
            <tr>
                <td>{{ $deal->owner_name }}</td>
                <td>{{ $deal->lead_name }}</td>
                <td>{{ $deal->created_at }}</td>
                <td>{{ $deal->project_name }}</td>
                <td>{{ $deal->country_province }}</td>
                <td>{{ $deal->section_plot }}</td>
                <td>{{ $deal->block_num }}</td>
                <td>{{ $deal->floor_number }}</td>
                <td>{{ $deal->room_number }}</td>
                <td>{{ $deal->gross_square }}</td>
                <td>{{ $deal->flat_num }}</td>
                <td>{{ $deal->reservation_amount }}</td>
                <td>{{ $deal->sale_price }}</td>
                <td>{{ $deal->excerpt }}</td>
                <td>
                    {{ $deal->payment_type === 1 ? 'Cash' : 'Installment' }}
                </td>
                <td>{{ $deal->down_payment }}</td>
                <td>{{ $deal->payment_discount }}</td>

            </tr>
        @endforeach
        <tr class="item last">
            <td>
                {{ __('Total deals in this page:') }}
            </td>
            <td>
                {{ $deals->count() }} Record(s)
            </td>
        </tr>
        <tr class="total">
            <td>
                {{ __('Report Generated by:') }}
            </td>
            <td>
                {{ auth()->user()->name }}
            </td>
        </tr>
        <tr class="total">
            <td>
                {{ __('Generated on:') }}
            </td>
            <td>
                {{ \Carbon\Carbon::now()->format('Y-m-d g:i a') }}
            </td>
        </tr>
    </table>
</div>
<div>
</div>
</body>
